// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/glock.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LockRequest struct {
	Resource             string   `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Requester            string   `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	Expire               int32    `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockRequest) Reset()         { *m = LockRequest{} }
func (m *LockRequest) String() string { return proto.CompactTextString(m) }
func (*LockRequest) ProtoMessage()    {}
func (*LockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_glock_16a67af58c88bb44, []int{0}
}
func (m *LockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockRequest.Unmarshal(m, b)
}
func (m *LockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockRequest.Marshal(b, m, deterministic)
}
func (dst *LockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockRequest.Merge(dst, src)
}
func (m *LockRequest) XXX_Size() int {
	return xxx_messageInfo_LockRequest.Size(m)
}
func (m *LockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockRequest proto.InternalMessageInfo

func (m *LockRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *LockRequest) GetRequester() string {
	if m != nil {
		return m.Requester
	}
	return ""
}

func (m *LockRequest) GetExpire() int32 {
	if m != nil {
		return m.Expire
	}
	return 0
}

type LockReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockReply) Reset()         { *m = LockReply{} }
func (m *LockReply) String() string { return proto.CompactTextString(m) }
func (*LockReply) ProtoMessage()    {}
func (*LockReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_glock_16a67af58c88bb44, []int{1}
}
func (m *LockReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockReply.Unmarshal(m, b)
}
func (m *LockReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockReply.Marshal(b, m, deterministic)
}
func (dst *LockReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockReply.Merge(dst, src)
}
func (m *LockReply) XXX_Size() int {
	return xxx_messageInfo_LockReply.Size(m)
}
func (m *LockReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LockReply.DiscardUnknown(m)
}

var xxx_messageInfo_LockReply proto.InternalMessageInfo

func (m *LockReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*LockRequest)(nil), "glock.LockRequest")
	proto.RegisterType((*LockReply)(nil), "glock.LockReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LockerClient is the client API for Locker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LockerClient interface {
	Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockReply, error)
	RLock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockReply, error)
	Unlock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockReply, error)
}

type lockerClient struct {
	cc *grpc.ClientConn
}

func NewLockerClient(cc *grpc.ClientConn) LockerClient {
	return &lockerClient{cc}
}

func (c *lockerClient) Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockReply, error) {
	out := new(LockReply)
	err := c.cc.Invoke(ctx, "/glock.Locker/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockerClient) RLock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockReply, error) {
	out := new(LockReply)
	err := c.cc.Invoke(ctx, "/glock.Locker/RLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockerClient) Unlock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockReply, error) {
	out := new(LockReply)
	err := c.cc.Invoke(ctx, "/glock.Locker/Unlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LockerServer is the server API for Locker service.
type LockerServer interface {
	Lock(context.Context, *LockRequest) (*LockReply, error)
	RLock(context.Context, *LockRequest) (*LockReply, error)
	Unlock(context.Context, *LockRequest) (*LockReply, error)
}

func RegisterLockerServer(s *grpc.Server, srv LockerServer) {
	s.RegisterService(&_Locker_serviceDesc, srv)
}

func _Locker_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockerServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glock.Locker/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockerServer).Lock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Locker_RLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockerServer).RLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glock.Locker/RLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockerServer).RLock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Locker_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockerServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glock.Locker/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockerServer).Unlock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Locker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "glock.Locker",
	HandlerType: (*LockerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lock",
			Handler:    _Locker_Lock_Handler,
		},
		{
			MethodName: "RLock",
			Handler:    _Locker_RLock_Handler,
		},
		{
			MethodName: "Unlock",
			Handler:    _Locker_Unlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/glock.proto",
}

func init() { proto.RegisterFile("proto/glock.proto", fileDescriptor_glock_16a67af58c88bb44) }

var fileDescriptor_glock_16a67af58c88bb44 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xcf, 0xc9, 0x4f, 0xce, 0xd6, 0x03, 0xb3, 0x85, 0x58, 0xc1, 0x1c, 0xa5, 0x78,
	0x2e, 0x6e, 0x9f, 0xfc, 0xe4, 0xec, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x29, 0x2e,
	0x8e, 0xa2, 0xd4, 0xe2, 0xfc, 0xd2, 0xa2, 0xe4, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x38, 0x5f, 0x48, 0x86, 0x8b, 0xb3, 0x08, 0xa2, 0x2c, 0xb5, 0x48, 0x82, 0x09, 0x2c, 0x89, 0x10,
	0x10, 0x12, 0xe3, 0x62, 0x4b, 0xad, 0x28, 0xc8, 0x2c, 0x4a, 0x95, 0x60, 0x56, 0x60, 0xd4, 0x60,
	0x0d, 0x82, 0xf2, 0x94, 0xa4, 0xb9, 0x38, 0x21, 0x16, 0x14, 0xe4, 0x54, 0x0a, 0xf1, 0x71, 0x31,
	0xe5, 0x67, 0x83, 0x0d, 0xe6, 0x08, 0x62, 0xca, 0xcf, 0x36, 0x9a, 0xcd, 0xc8, 0xc5, 0x06, 0x92,
	0x4d, 0x2d, 0x12, 0xd2, 0xe3, 0x62, 0x01, 0xb1, 0x84, 0x84, 0xf4, 0x20, 0xae, 0x44, 0x72, 0x95,
	0x94, 0x00, 0x8a, 0x58, 0x41, 0x4e, 0xa5, 0x12, 0x83, 0x90, 0x3e, 0x17, 0x6b, 0x10, 0x49, 0x1a,
	0x0c, 0xb8, 0xd8, 0x42, 0xf3, 0x72, 0x48, 0xd0, 0xe1, 0xc4, 0x1e, 0xc5, 0x0a, 0x0e, 0xab, 0x24,
	0x36, 0x30, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x62, 0x98, 0x15, 0xe2, 0x47, 0x01, 0x00,
	0x00,
}
